### ISSUE TITLE
关于Monibuca许可疑问

### ISSUE THREAD

**Issue by ChungTak** [Monibuca/engine#1]
dexter~你好，请问Monibuca用于商用需要付费吗？官方插件项目没有著名许可协议，是不是支持engine才是GPL协议，官方插件不是呢？如果是自己写的插件有没有限制呢？

**Comment by langhuihui** [comment]
你好，Monibuca是完全开源的，可以商用，不需要付费！自己写的插件也不受限制。另外欢迎为开源项目贡献你的一份力量。商业项目也可以一起合作^_^。GPL协议是防止一些恶意的情况发生，不用担心使用哈。

**Comment by ChungTak** [comment]
感谢你的回复！我倒是觉得插件市场可以收费，rtmp,hls这些基础免费～～譬如onvif那些行业专有的收费

**Comment by langhuihui** [comment]
很对，我正在思考如何实现插件的授权机制

**Comment by langhuihui** [comment]
V3 分支已改为MIT协议
