### ISSUE TITLE
engine v4.14.6内置鉴权bug

### ISSUE THREAD

**Issue by wangyg115** [Monibuca/engine#100]
1、问题描述：
engine v4.14.6, 启用内置鉴权后，使用rtmp推流，expire参数验证通过后，当rsecret参数长度小于16， 系统崩溃退出。
2、fatal日志：
panic: runtime error: slice bounds out of range [:28] with length 27
goroutine 13 [running]:
m7s.live/engine/v4.(*IO).auth(0xc0002f0000, {0xc000dfa0d0, 0x6}, {0xc0015fee11, 0x1b}, {0xc0015fee34, 0x8})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.14.6/io.go:152 +0x1f0

**Comment by langhuihui** [comment]
确实，应该判断一下长度的
