### ISSUE TITLE
H265编码格式的流兼容codec和enhance-rtmp两个格式的推流

### ISSUE THREAD

**Issue by 2hangchen** [Monibuca/engine#101]

**Comment by langhuihui** [comment]
推流两种都兼容的，你要的是拉流也要两种都有对吧

**Comment by 2hangchen** [comment]
> 推流两种都兼容的，你要的是拉流也要两种都有对吧

对，拉流，前几天在群里提过，我提个issure记录一下，到时候方便学习一下改动点

**Comment by langhuihui** [comment]
我想了一下，拉流都兼容比较麻烦，因为你不知道对方需要什么，如果通过参数指定的话，需要在 engine 中提前存储两种结构，如果临时组织结构，就需要增加额外开销。

**Comment by 2hangchen** [comment]
> 我想了一下，拉流都兼容比较麻烦，因为你不知道对方需要什么，如果通过参数指定的话，需要在 engine 中提前存储两种结构，如果临时组织结构，就需要增加额外开销。

能不能在[plugin-jessica](https://github.com/Monibuca/plugin-jessica)插件上进行适配，如果是播ws-flv，就走enhance，如果要播codec12的，基于现在的playraw重组一次codec的包转出去，这样的话就不用在引擎里同时存两种了，只有需要codec12的时候进行临时组织结构，这个开销我觉得可以接受吧

**Comment by 2hangchen** [comment]
这个问题解决了？ @langhuihui

**Comment by langhuihui** [comment]
不支持 codec12 播放了
