### ISSUE TITLE
关于丢帧率有一个疑问？

### ISSUE THREAD

**Issue by YoooDT** [Monibuca/engine#102]
1、在engine/track/base.go中。计算丢帧率drops = dropcount / elapse 
2、计算丢包率应该是丢的包 / 发的总数吧？ 
3、在一段时间间隔内 dropcount是丢包数
4、在一段时间间隔发的总数 是不是应该用两个变量 beginSeq  endSeq 记录一下
5、丢包率是不是应该 = dropcount/ (endSeq - beginSeq) *100% -- 需要特殊处理65535->0

**Comment by langhuihui** [comment]
是这样的，engine 其实无法计算丢包率，因为不同的协议有不同的行为，这里只是给个存储的地方
