### ISSUE TITLE
internal=true 内部订阅者在publishtimeout超时后被断开

### ISSUE THREAD

**Issue by luowencai** [Monibuca/engine#108]
根据日志来看，是触发了last leave:
![image](https://github.com/Monibuca/engine/assets/16441807/92f77944-10a9-4d0f-a91b-e50bef35513c)
![无标题](https://github.com/Monibuca/engine/assets/16441807/a557b08b-078b-4e87-a9c6-8560e5399d37)
 从代码上看是在519行的s.Subscribers.Len()==0 这里判断没有把内部订阅者的数量包括进去，导致触发了last leave，这个是否是正常的？

**Comment by langhuihui** [comment]
正常，之所以有内部订阅者的概念，就是为了 last leave 能够触发，否则比如有录制订阅者，导致永远无法触发 last leave
