### ISSUE TITLE
使用rtmp插件拉去流在同步推流有问题 推流会导致第三方rtmp平台出现rtmp消息长度为0 缓冲区也为0

### ISSUE THREAD

**Issue by wuyou0123** [Monibuca/engine#114]
现在在不同网络下的机器上部署了两台m7s（机器端口是相通的） a和b 其中b流媒体通过rtmp协议去另一台m7s上拉流，然后再将拉取的流通过rtmp协议推给 第三方rtmp服务器，第三方服务器按照rtmp标准协议处理总是会检测到m7s传过来的rtmp消息长度为0，并且缓冲区大小也为 0 然后关闭链接，如何在m7s rtmp插件里netConnection.go里面SendMessage方法和sendChunk做处理，我这边处理了对b的m7s中writeBuffer为0的设置了默认缓冲区，并且在sendChunk方法中重新比较conn.chunkHeader和uint32(range writeBuffer)大小 并赋值又会影响到a的m7s， a流媒体不在推给b服务  下面是我在b流媒体服务更改的代码
![1EEE3E5A-5345-40c5-B78B-ABE52A222800](https://github.com/user-attachments/assets/0de0b360-8f30-4adf-8ee9-17cf3b5973ee)
![1726716873001_0B0BB4FA-FA30-485a-AC51-F51F00C3F8E1](https://github.com/user-attachments/assets/a8d3c74a-e064-43c6-8fdd-1a6308664b07)
这是b流媒体服务最近停止推流的日志
![image](https://github.com/user-attachments/assets/e64bdc34-84e6-4be5-ae29-47dd697e8aac)

**Comment by langhuihui** [comment]
长度为0 的消息类型是什么

**Comment by wuyou0123** [comment]
> 长度为0 的消息类型是什么

我这边打印日志最后一次报错的类型是20 
![image](https://github.com/user-attachments/assets/2a3ba8df-f4a9-4cdb-8a31-86b90109d268)

**Comment by langhuihui** [comment]
你打个断点看一下 tmpBuf 长度为 0 的时候 msg 是什么

**Comment by wuyou0123** [comment]
> 你打个断点看看一下 tmpBuf 长度为 0 的时候 msg 是什么

> 问题就处在这。我打印日志并未出现tmpBuf =0 ，我看了第三方rtmp报错日志，是不是存在消息长度小于
‘缓冲’大小报的异常,
>  这是m7s代码日志输出，没有打印出0, 第二张图是第三方使用go-rtmp依赖报错地方的代码

![1726722385842_A7529901-2B3E-4326-97C1-105F279EB3FB](https://github.com/user-attachments/assets/dc7979b7-d903-4b20-ab37-84b8c82e82d0)

![1726722372595_9B2AE564-AC08-4f06-9491-EA6A1DFC6FC0](https://github.com/user-attachments/assets/1953cc87-b4e3-44a4-89c4-e9fa34f5d6b2)

**Comment by langhuihui** [comment]
我没看明白，到底哪里是 0

**Comment by wuyou0123** [comment]
> 哪里是
我打印m7s rtmp协议发送的消息conn.tmpBuf.Len()的长度并未出现0 ，但是第三方rtmp服务器确实报这个异常，并关闭连接
异常信息：message length (0) higher than buffer size (0

**Comment by langhuihui** [comment]
你是说 MessageLength 是 0？那我发送的时候有发送 MessageLength 为 0 的包吗？

**Comment by wuyou0123** [comment]
> MessageLength

这个倒没有，有没有这种可能，MessageLength 不是0 但是小于缓冲区长度 所以异常了
如果只通过一台流媒体直接推流到第三方rtmp流媒体上就是正常的，但是通过rtmp协议先拉取另一台m7s流媒体上的设备，在同步推流到第三方rtmp就出现这个问题了，你们有试过这种场景么

**Comment by langhuihui** [comment]
从你说的异常信息：message length (0) higher than buffer size (0 来看说明有 MessageLength 为 0 的情况

**Comment by wuyou0123** [comment]
> than
是的，你们可以试下我这种场景边拉边推到别的rtmp服务器上看看，因为我这边对这个了解也不多

**Comment by langhuihui** [comment]
你可以再起一个 c，推到 c 试试

**Comment by wuyou0123** [comment]
> 再起一个 c，推到 c 试试
我又起了个c的m7s 步骤是 b通过rtmp先拉取a的流媒体然后再通过rtmp接口将本地流推到c的服务中，也出现问题了
c的服务报错如下：
![image](https://github.com/user-attachments/assets/2bb8b80c-b0c6-4b9b-acc0-756de1b8cc9f)

**Comment by langhuihui** [comment]
那确实有问题

**Comment by wuyou0123** [comment]
> 那确实有问题

请问咋解决

**Comment by langhuihui** [comment]
我得测试一下

**Comment by langhuihui** [comment]
大概需要多久出现

**Comment by wuyou0123** [comment]
> 需要多久出现

1到2秒

**Comment by langhuihui** [comment]
我自己测试没有出现，是不是和视频源有关系

**Comment by wuyou0123** [comment]
> 测试没有出现，是不是和视频源有关系
单个流媒体推就没问题，先拉再推就出现了

**Comment by langhuihui** [comment]
我就是先拉再推的，你看看是不是版本太低

**Comment by wuyou0123** [comment]
> 我就是先拉再推的，你看看是不是版本太低

用的是1.8.0版本的

**Comment by langhuihui** [comment]
啥呀

**Comment by wuyou0123** [comment]
> 我就是先拉再推的，你看看是不是版本太低

我拉下新代码试试

**Comment by wuyou0123** [comment]
> 我就是先拉再推的，你看看是不是版本太低

是版本问题。非常感谢
