### ISSUE TITLE
建议核心引擎添加 RTP forward功能

### ISSUE THREAD

**Issue by ChungTak** [Monibuca/engine#2]
建议参考janus的 RTP forward功能,如果Monibuca能接收 其他网关的RTP forward 和输出 RTP forward，就可以轻松实现：
1) rtmp/rtsp... -> Monibuca  rtp -> janus(media soup ...) webrtc 
2) Monibuca  rtp -> 人工智能分析(人脸识别，车辆识别) -> 结构化数据
3) Monibuca  rtp ->  ffmpge/gstream  -> Monibuca rtp (Monibuca遵循轻量不做编解码，由外部做)
4) Monibuca  rtp -> Monibuca  rtp   实现Monibuca之间的级联
5) Monibuca  rtp  <-> sip(freeswitch)
_参考资料：janus 在 fosdem 2020 的演讲ppt
https://fosdem.org/2020/schedule/event/janus/attachments/audio/3993/export/events/attachments/janus/audio/3993/fosdem2020_janus_rtp_forwarders.pdf
作者提到janus的下一步开发计划"Maybe implement RTP forwarding as a core feature instead?"_

**Comment by langhuihui** [comment]
相当于monibuca可以向外推流？

**Comment by ChungTak** [comment]
相向。支持接收raw rtp ，也支持向外推流raw rtp
janus 的 rtpforwad 和 mediasoup 的PlainRtpTransport(PlainRtpTransport) 实现的就是这样的功能

**Comment by langhuihui** [comment]
这个功能应该不难实现，而且不需要在引擎中实现，做成一个插件即可

**Comment by langhuihui** [comment]
rtp格式已经成为engine缓存中的一部分
