### ISSUE TITLE
rtmp推流有问题

### ISSUE THREAD

**Issue by tinyjoy4code** [Monibuca/engine#25]
windows10下：
推流：
ffmpeg -i test.mp4 -f flv rtmp://localhost/live/test

![image](https://user-images.githubusercontent.com/7285166/148744828-3e8d76ce-ae06-4dc6-af31-66f9cd33edff.png)

拉流：
ffplay -i rtmp://localhost/live/test

![image](https://user-images.githubusercontent.com/7285166/148744952-b433902c-768d-4e03-9016-5064348f9570.png)

拉流订阅后就退出了：
![image](https://user-images.githubusercontent.com/7285166/148744365-689067ae-0c39-4019-b9a7-5ab81868d599.png)

以为是拉流的问题，后面跟代码发现，是推流不正常！

![image](https://user-images.githubusercontent.com/7285166/148745770-cd272012-45ed-4f65-9f8f-e8541dfff212.png)

也就是PushByteStream()函数进来后，只做了下判断，啥也没干... 对RTMP协议不是很熟悉，前面对msg包的处理逻辑看的不是很明白，是前面对msg包处理的问题还是其他情况？

**Comment by langhuihui** [comment]
你用最新的版本试试呢

**Comment by tinyjoy4code** [comment]
刚刚试了下最新版本，也还是一样的...
![image](https://user-images.githubusercontent.com/7285166/148900271-9fbc5e0b-c179-4cb9-b4fb-caee20ca97e3.png)

我还试了下官网首页，那个编译好的，也是一样的...
![image](https://user-images.githubusercontent.com/7285166/148900682-2c2c26af-f76a-44a0-a4d1-6b22b42b1921.png)

另外，官网这个新改版，个人觉得好阴间风啊！！！还是原先的比较简洁，看着舒服一些...

**Comment by langhuihui** [comment]
我看了一下ffmpeg输出的是flv1格式的视频，你可以通过参数来配置输出h264格式就行了

**Comment by tinyjoy4code** [comment]
ffmpeg -i test.MP4 -f h264 rtmp://localhost/live/test 这样？ 也不行，还报了一些错误...
![image](https://user-images.githubusercontent.com/7285166/148912910-abd777ee-5818-4544-8445-1c97c81cc577.png)

这个意思是推流不支持flv格式么？RTMP不是一般都是flv格式的么？
文档上写的也是 -f flv啊...

**Comment by langhuihui** [comment]
-c:v h264    你可以百度一下啊

**Comment by tinyjoy4code** [comment]
理解有偏差，- - ！这样就可以了！ 
ffmpeg -i test.mp4 -c:v libx264 -f flv rtmp://localhost/live/test

感谢 @langhuihui 的回复！

附上ffmpeg官方文档：https://www.ffmpeg.org/ffmpeg.html
