### ISSUE TITLE
小白请教：普通的视频服务网站需要这样的架构吗？

### ISSUE THREAD

**Issue by 3xxx** [Monibuca/engine#3]
大神您好，看了您发的很多资料，近段时间一直有个疑问，不需要直播的网站，只是播放一下视频，服务端也需要设计成这样么？需要推流吗？因为在html里插入的mp4文件，浏览器也能播放，是否因为考虑性能才需要这样的服务？
感谢您百忙之中解惑。您这个项目真是非常贴心。

**Comment by langhuihui** [comment]
如果是单纯点播服务，不需要流媒体服务器，只需要Nginx这样的静态资源服务器即可。

**Comment by 3xxx** [comment]
感谢大神这么热心解惑。
