### ISSUE TITLE
如何将订阅流转为图片

### ISSUE THREAD

**Issue by donetkit** [Monibuca/engine#37]
如何将订阅流转为图片

**Comment by sandcu** [comment]
ffmpeg单拉一路流做转换把

**Comment by langhuihui** [comment]
目前增加了截图插件，可以将视频中的关键帧转换成图片

**Comment by donetkit** [comment]
> 目前增加了截图插件，可以将视频中的关键帧转换成图片

好的 请问截图插件是哪个 能否给个链接呢

**Comment by langhuihui** [comment]
github.com/Monibuca/plugin-snap
