### ISSUE TITLE
没有 benchmark？

### ISSUE THREAD

**Issue by bigbao9494** [Monibuca/engine#4]
没有 benchmark？或者测试用发布的bin文件？

**Comment by langhuihui** [comment]
还没来得及弄

**Comment by bigbao9494** [comment]
弄一个呗，比如可以和业内的SRS这些做人对比，方便大家了解一下。

**Comment by bigbao9494** [comment]
启动后推流成功，hls,rtsp怎么播放的呢？只播起了RTMP

2020/06/06 21:28:54 install plugin Cluster v1.0.0
2020/06/06 21:28:54 install plugin GateWay v1.2.4
2020/06/06 21:28:54 install plugin HDL v1.2.1
2020/06/06 21:28:54 install plugin TS v1.2.1
2020/06/06 21:28:54 install plugin HLS v1.0.0
2020/06/06 21:28:54 install plugin Jessica v1.2.5
2020/06/06 21:28:54 install plugin LogRotate v1.2.3
2020/06/06 21:28:54 install plugin Record v1.0.2
2020/06/06 21:28:54 install plugin RTMP v1.2.2
2020/06/06 21:28:54 install plugin RTSP v1.1.4
2020/06/06 21:28:54 install plugin WebRTC v0.0.0-20200531020350-20fa49d8ed1e
2020/06/06 21:28:54 start monibuca v2.1.0
2020/06/06 21:28:54 server bare start at :2019
2020/06/06 21:28:54 server Jessica start at :8080
2020/06/06 21:28:54 HDL start at  :2020
2020/06/06 21:28:54 server rtmp start at :1935
2020/06/06 21:28:54 server gateway start at  :8081
2020/06/06 21:28:55 start report summary
2020/06/06 21:28:58 app:live,objectEncoding:<nil>
2020/06/06 21:28:58 createStream: 65
2020/06/06 21:28:58 Stream create: live/livestream
2020/06/06 21:29:13 <<<

**Comment by langhuihui** [comment]
rtsp播放功能还没做 ，hls目前只有写磁盘功能，可以配合Nginx来播放，SRS是C++的性能没有它强，但是源码可读性和可扩展性肯定比SRS强

**Comment by langhuihui** [comment]
最新HLS插件已支持播放，播放地址类似http://localhost:8081/hls/live/livestream.m3u8

**Comment by langhuihui** [comment]
rtsp播放已经支持
