### ISSUE TITLE
engine go build error:invalid character U+007E '~'

### ISSUE THREAD

**Issue by bigdatabody** [Monibuca/engine#40]
[root@localhost engine]# go build
# m7s.live/engine/v4/util
util/big_endian.go:4:2: invalid character U+007E '~'
util/big_endian.go:4:7: syntax error: unexpected |, expecting semicolon or newline or }
util/big_endian.go:7:6: missing function body
util/big_endian.go:7:11: syntax error: unexpected [, expecting (
util/big_endian.go:14:6: missing function body
util/big_endian.go:14:12: syntax error: unexpected [, expecting (
util/big_endian.go:22:6: missing function body
util/big_endian.go:22:11: syntax error: unexpected [, expecting (

**Comment by langhuihui** [comment]
请升级go到1.18+
