### ISSUE TITLE
【建议】服务端添加流状态校验 目前：使用面板或者调用API关闭流，推流端无感知。

### ISSUE THREAD

**Issue by husanpao** [Monibuca/engine#44]
- 使用obs，ffmpeg等推流工具推流到m7s ,然后使用面板或者调用API关闭流，推流端无感知，无异常，持续推流。

> 应该加个api或面板将流关闭后，即关闭推流通道

-

**Comment by langhuihui** [comment]
已经增加了配置，rtmp插件中增加自动关闭配置，如果推流结束会关闭连接，默认这个配置生效
