### ISSUE TITLE
插件开发文档不是最新的吗？

### ISSUE THREAD

**Issue by chekun** [Monibuca/engine#45]
按照文档描述，貌似有的方法不存在了？

<img width="520" alt="image" src="https://user-images.githubusercontent.com/1967804/172117269-4c272402-7bac-45ec-af8d-7b44b11ad5e7.png">

**Comment by langhuihui** [comment]
嗯，这边文档没及时更新

**Comment by langhuihui** [comment]
IPublisher这个case只是展示了一下这个事件，里面的逻辑已经封装好了，不需要你再写一遍

**Comment by chekun** [comment]
好的，感谢老大，我再摸索一下
