### ISSUE TITLE
支持不同流之间转发吗？

### ISSUE THREAD

**Issue by gooodwu** [Monibuca/engine#48]

**Comment by langhuihui** [comment]
这是最基本的功能

**Comment by gooodwu** [comment]
localhost:8080/webrtc/play?streamPath=live/123456
webrtc play  api body中的sdp参数请求有没有例子呀？
一直报这个错误
SetRemoteDescription called with no ice-ufrag

**Comment by gooodwu** [comment]
rtmp mpeg4-generic 音频编码是否支持转 webrtc  ？

**Comment by langhuihui** [comment]
aac需要转码才能支持webrtc
