### ISSUE TITLE
go get 失败

### ISSUE THREAD

**Issue by bigbao9494** [Monibuca/engine#5]
C:\Users\Administrator>go get github.com/Monibuca/monica
unrecognized import path "golang.org/x/sys/windows": https fetch: Get "https://g
olang.org/x/sys/windows?go-get=1": dial tcp 216.239.37.1:443: connectex: A conne
ction attempt failed because the connected party did not properly respond after
a period of time, or established connection failed because connected host has fa
iled to respond.

**Comment by langhuihui** [comment]
golang.org被墙的缘故。参考https://zhuanlan.zhihu.com/p/141181279
