### ISSUE TITLE
V4 重新拉流异常

### ISSUE THREAD

**Issue by FireTiger23** [Monibuca/engine#51]
rtsp:
  pull:
    repull: -1

配置不限次数重新拉流
![6ff5db780f738d80015c4eec948cc45](https://user-images.githubusercontent.com/6301010/179740174-7e35ca62-0e54-4bc7-a655-7c4157d323b0.jpg)
但是 流无法播放。

这个时候再手动同参数进行拉流  倒是可以。

**Comment by langhuihui** [comment]
看上去是流的状态没有变对导致的，我研究一下
