### ISSUE TITLE
v4版本如何推流鉴权？

### ISSUE THREAD

**Issue by sapceman** [Monibuca/engine#58]
请问在自定义插件中的OnEvent方法接收哪个事件中处理？现在我在“SEpublish”事件中通过Stream.Close()的方法进行处理，因为obs有断线重连功能，就出现反复连接->断开，感觉这样不是很友好。

**Comment by langhuihui** [comment]
鉴权的话，分为推流和拉流，你这种情况应该属于推流，推流的话需要在具体的插件中找到调用plugin.Publish 的部分，在那里进行判断，是否要关闭当前的tcp连接达到使得OBS推流失败的效果

**Comment by sapceman** [comment]
我用Stream.Close()这个方法是因为我看到/api/closestream?streamPath=xxx这个api也是用的Stream.Close()，刚试了一下，/api/closestream?streamPath=xxx关闭一个流后，也会因为obs断线重连功能马上又连上，不知道这样设计是否合理？

**Comment by langhuihui** [comment]
这个close是关闭m7s的流的，但是具体插件有具体的tcp连接，obs的判断是如果推流成功，那么断开后就要重连

**Comment by sapceman** [comment]
> 这个close是关闭m7s的流的，但是具体插件有具体的tcp连接，obs的判断是如果推流成功，那么断开后就要重连

请问大神， 在自定义插件中关闭某一个m7s的流的同时，如何关闭这个流对应的tcp连接？谢谢！

**Comment by langhuihui** [comment]
已经增加了鉴权机制，请参考开发文档中的鉴权一栏
