### ISSUE TITLE
rtmp推流异常

### ISSUE THREAD

**Issue by sapceman** [Monibuca/engine#59]
rtmp配置kickexist: true后，两个obs用相同的地址进行推流，m7s异常退出了，生成fatal.log：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xfde0a9]

goroutine 105 [running]:
m7s.live/engine/v4.(*Stream).action(0xc00039f790, 0x2)
	……/m7s/workspace/engine/stream.go:226 +0x3e9
m7s.live/engine/v4.(*Stream).run(0xc00039f790)
	……/m7s/workspace/engine/stream.go:394 +0x1a5e
created by m7s.live/engine/v4.findOrCreateStream
	……/m7s/workspace/engine/stream.go:206 +0x55f

**Comment by langhuihui** [comment]
我来修复一下
