### ISSUE TITLE
API可否增加一个状态通知接口

### ISSUE THREAD

**Issue by echome123** [Monibuca/engine#60]
配置文件当中配置一个全局API接口地址，当系统中的流任务有新增，断开，出错，开始录制，结束录制等等状态时候，都给API接口发一个回调通知。
目前我发现只能通过API去循环检测各种list内容，效率比较低，而且控制台对各种状态都有输出，不知道是否能考虑增加一下。

**Comment by langhuihui** [comment]
这个有专门的插件解决，https://m7s.live/guide/plugins/hook.html

**Comment by echome123** [comment]
> 这个有专门的插件解决，https://m7s.live/guide/plugins/hook.html

  感谢感谢，是我没认真看文档，Monibuca万岁
