### ISSUE TITLE
macos无法多次启停无法推流

### ISSUE THREAD

**Issue by ponycloud235** [Monibuca/engine#61]
使用系统：macos 10.15
步骤描述：
1. 启动go run main.go，设备拉流，播放正常
2. 使用sh shutdown.sh 关闭，调整参数再次启动
3. 启动正常，无法正常接收流，这是抓的包，发现正常认证，无法推流
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/2733701/197959276-8889f0fa-7cc8-4c84-8c4b-33136b074e94.png">
4.再次杀死sh shutdown.sh ,发现gb插件端口被占用，使用命令发现5060无进程占用
<img width="1581" alt="image" src="https://user-images.githubusercontent.com/2733701/197959501-54bd6f5c-0f3c-48f1-af0a-b8c7edb62adf.png">
<img width="321" alt="image" src="https://user-images.githubusercontent.com/2733701/197959581-1f29dee3-c37c-41d8-9bf9-da9e15248aba.png">

如果整台电脑重启，可恢复

**Comment by ponycloud235** [comment]
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/2733701/197968683-2880b513-c6f8-48c9-af3b-fac0147b48a6.png">
这个报错是否能定位问题？

**Comment by langhuihui** [comment]
配置文件写的有问题
