### ISSUE TITLE
直播流 flv 播放 音画不同步

### ISSUE THREAD

**Issue by mars79668** [Monibuca/engine#66]
使用 hls 拉取直播流， vlc播放flv时间越长音画不同步就越严重， 播放hls输出音画是同步的。
最新的v4版本

**Comment by langhuihui** [comment]
用ffplay播放是否也一样现象？

**Comment by mars79668** [comment]
问题找到了， 要进行流速控制
建议 默认开启流速控制，或者 等待上限 -1  自动控制

**Comment by langhuihui** [comment]
现在默认已经开启了
