### ISSUE TITLE
当Streams.Get(streamPath)取不到值时会抛出panic导致程序崩了

### ISSUE THREAD

**Issue by wangkaiyj** [Monibuca/engine#69]
plugin.go文件
第289行:   if puber := Streams.Get(streamPath).Publisher; puber != puller && puber != nil {
当Streams.Get(streamPath)取不到值时会抛出panic导致程序崩了，最好是使用Streams.Has(streamPath)提前先判断一下

**Comment by langhuihui** [comment]
确实如此，我改正
