### ISSUE TITLE
空指针引发panic问题

### ISSUE THREAD

**Issue by hydaizd** [Monibuca/engine#74]
track/reader-av.go中，item空指针引发panic问题
```go
func (r *AVRingReader) TryRead() (item *common.AVFrame) { 
	if item = &r.Value; item.CanRead {
		return
	}
	return nil
}
```

**Comment by hydaizd** [comment]
v4.11.9版本

**Comment by langhuihui** [comment]
怎么操作的，item正常不可能是nil的

**Comment by hydaizd** [comment]
从这里拉取的源码：https://github.com/langhuihui/monibuca
当时引擎用的是v4.11.9版本，然后本地用windows环境跑起来，接入了一台支持gb28181的摄像头，使用webrtc方式播放，运行一会儿后发现程序异常退出，就是这个错误引起的。

**Comment by langhuihui** [comment]
好的，我来测试一下看看

**Comment by langhuihui** [comment]
找到原因了
