### ISSUE TITLE
在解析配置文件时，插件配置中的独有属性，不能被正常写入到对应插件中

### ISSUE THREAD

**Issue by daxiong0327** [Monibuca/engine#75]
eg:
在配置文件中，给record插件设置flv格式的fragment时间不为0。在录制时record的fragment依旧时0；

**Comment by langhuihui** [comment]
你是不是写错格式了，现在这个fragment需要加单位，比如10s不能写10

**Comment by daxiong0327** [comment]
奥对，我测试了一下，加上单位是可以的
