### ISSUE TITLE
热更新配置接口

### ISSUE THREAD

**Issue by YoooDT** [Monibuca/engine#80]
1.调用热更新配置接口或者先modify再热更新,会报错
2.具体错误 Unmarshal error:reflect : NumField of non-struct type config.Plugin

**Comment by langhuihui** [comment]
具体更新的是哪个插件？，详细点日志呢

**Comment by YoooDT** [comment]
> 具体更新的是哪个插件？，详细点日志呢

engine/http.go -> API_updateConfig接口 

http请求:   ip:port/api/updateconfig?name=Hook

**Comment by langhuihui** [comment]
找到原因了，下个版本修复

**Comment by YoooDT** [comment]
> 找到原因了，下个版本修复

具体什么原因呢，我看看如果简单我先本地改了使用

**Comment by langhuihui** [comment]
func (opt *Plugin) Update(conf config.Config) {
	conf.Unmarshal(opt.Config)
	opt.Config.OnEvent(conf)
}

**Comment by DonieGeng** [comment]
修改后还有问题
![image](https://user-images.githubusercontent.com/26532883/230808428-ad789cbb-f48c-4361-8525-c5cbab5a30ab.png)
![image](https://user-images.githubusercontent.com/26532883/230808481-59efc1cb-5354-4ffe-b670-8521d56dc905.png)
错误信息如下
![image](https://user-images.githubusercontent.com/26532883/230808546-9952b1d0-f836-4d83-93d0-41fcfccf08fa.png)

**Comment by langhuihui** [comment]
modify时带上参数yaml=1  body里面传入yaml格式的参数。原因——json反序列化和yaml不同，无法将map自动转换成Config类型
