### ISSUE TITLE
发现长时间运行内存持续上涨

### ISSUE THREAD

**Issue by daxiong0327** [Monibuca/engine#82]
![image](https://user-images.githubusercontent.com/79887694/232722645-3212b263-219b-402c-889a-f6811662c435.png)

**Comment by langhuihui** [comment]
你使用了什么协议呢？提供更详细的情况

**Comment by daxiong0327** [comment]
用rtmp给engine推流

**Comment by daxiong0327** [comment]
有pprof的heap文件，可以吧

**Comment by langhuihui** [comment]
可以，你直接输出svg吧

**Comment by daxiong0327** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monibuca/engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monibuca/engine] 发现长时间运行内存持续上涨 (Issue #82)





 
你使用了什么协议呢？提供更详细的情况

**Comment by daxiong0327** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monibuca/engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monibuca/engine] 发现长时间运行内存持续上涨 (Issue #82)





 
可以，你直接输出svg吧

**Comment by daxiong0327** [comment]
感觉svg看不清楚




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Monibuca/engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Monibuca/engine] 发现长时间运行内存持续上涨 (Issue #82)





 
可以，你直接输出svg吧

**Comment by langhuihui** [comment]
我的微信加了吗？yigehui

**Comment by langhuihui** [comment]
找到原因：rtmp断开重推时没有将新的pool替换老的
