### ISSUE TITLE
Config parser incorrectly ignores YAML tags in config structs

### ISSUE THREAD

**Issue by abrar71** [Monibuca/engine#84]
The YAML parser in the config file is currently not respecting the `yaml` tag present in our custom plugin configuration struct
```go
MyCustomOption string `yaml:"my_custom_option"`
```
like this ->

```go
type MyPluginConfig struct {
  config.HTTP
  config.Publish
  config.Pull
  config.Subscribe
  config.Push
  MyCustomOption string `yaml:"my_custom_option"`
}
```

Technically the config parser should search for `my_custom_option` in the `yaml` config but the issue is it tries to find `mycustomoption` and doesn't use the `yaml` tag from plugin struct.

This behavior contradicts the expected usage of the yaml tag in the struct, which is meant to provide a clear mapping between the struct field and the corresponding key in the YAML configuration.

**Comment by langhuihui** [comment]
indeed

**Comment by langhuihui** [comment]
done！
