### ISSUE TITLE
AddPush方法

### ISSUE THREAD

**Issue by stdawn** [Monibuca/engine#85]
![image](https://github.com/Monibuca/engine/assets/13537943/ca0f36fb-344a-4e76-bab6-5d564c6e734a)
此处的key应该为streamPath
![image](https://github.com/Monibuca/engine/assets/13537943/c2dec795-b981-46cd-a53c-678c98dfa9f5)

**Comment by langhuihui** [comment]
确实有问题 PushList的key之所以是url，是因为远端地址对应的是一个流，也就是streamPath可以推向多个url，但一个url只有一个流对应，下面的循环要改一下

**Comment by langhuihui** [comment]
是应该改AddPush
