### ISSUE TITLE
使用obs推流rtmp到m7s，rtmp能正常播放，但是hsl播放不了

### ISSUE THREAD

**Issue by mijjjj** [Monibuca/engine#90]
obs配置
![image](https://github.com/Monibuca/engine/assets/37797122/7a1e6867-d404-457c-b34f-1ffa5a65ada6)

软件日志
![image](https://github.com/Monibuca/engine/assets/37797122/30659d23-e0fd-4188-a671-13ed441117e9)

api内容

{
  "StartTime": "2023-10-08T15:10:59.9241154+08:00",
  "PublishTimeout": 10000000000,
  "DelayCloseTimeout": 0,
  "IdleTimeout": 0,
  "PauseTimeout": 30000000000,
  "NeverTimeout": false,
  "Path": "live/test1",
  "Publisher": {
    "ID": "",
    "Type": "RTMPReceiver",
    "RemoteAddr": "",
    "StartTime": "2023-10-08T15:10:59.9241154+08:00",
    "Args": {

    },
    "Config": {
      "PubAudio": true,
      "PubVideo": true,
      "InsertSEI": false,
      "KickExist": false,
      "PublishTimeout": 10000000000,
      "WaitCloseTimeout": 0,
      "DelayCloseTimeout": 0,
      "IdleTimeout": 0,
      "PauseTimeout": 30000000000,
      "BufferTime": 0,
      "SpeedLimit": 500000000,
      "Key": "",
      "SecretArgName": "secret",
      "ExpireArgName": "expire",
      "RingSize": "256-1024"
    },
    "StreamID": 1
  },
  "State": 2,
  "SEHistory": [
    {
      "Time": "2023-10-08T15:10:59.9241154+08:00",
      "Action": 0,
      "From": 0
    },
    {
      "Time": "2023-10-08T15:11:05.1437876+08:00",
      "Action": 1,
      "From": 1
    }
  ],
  "Subscribers": [
    {
      "ID": "[::1]:57457|1",
      "Type": "RTMPSubscriber",
      "RemoteAddr": "",
      "StartTime": "2023-10-08T15:12:19.781481+08:00",
      "Args": {

      },
      "Config": {
        "SubAudio": true,
        "SubVideo": true,
        "SubVideoArgName": "vts",
        "SubAudioArgName": "ats",
        "SubDataArgName": "dts",
        "SubModeArgName": "mode",
        "SubAudioTracks": [],
        "SubVideoTracks": [],
        "SubDataTracks": [],
        "SubMode": 0,
        "SyncMode": 0,
        "IFrameOnly": false,
        "WaitTimeout": 10000000000,
        "WriteBufferSize": 0,
        "Key": "",
        "SecretArgName": "secret",
        "ExpireArgName": "expire",
        "Internal": false
      },
      "StreamID": 1
    }
  ],
  "Tracks": [
    {
      "Size": 256,
      "LastValue": {
        "DeltaTime": 21,
        "WriteTime": "2023-10-08T15:14:36.1630058+08:00",
        "Sequence": 10124,
        "BytesIn": 333,
        "IFrame": false,
        "PTS": 19440990,
        "DTS": 19440990,
        "Timestamp": 216011000000
      },
      "Name": "aac",
      "State": 0,
      "BPS": 16174,
      "FPS": 46,
      "Drops": 0,
      "RawSize": 331,
      "RawPart": [33, 26, 133, 144, 6, 16, 169, 101, 8, 116],
      "PayloadType": 97,
      "SSRC": 14639104,
      "SampleRate": 48000,
      "SequenceHeadSeq": 1,
      "CodecID": 10,
      "Channels": 2,
      "SampleSize": 16,
      "SizeLength": 13,
      "IndexLength": 3,
      "IndexDeltaLength": 3,
      "AVCCHead": "rwE=",
      "AudioObjectType": 2,
      "SamplingFrequencyIndex": 3,
      "ChannelConfiguration": 2,
      "FrameLengthFlag": 0,
      "DependsOnCoreCoder": 0,
      "ExtensionFlag": 0
    },
    {
      "Size": 256,
      "LastValue": {
        "DeltaTime": 17,
        "WriteTime": "2023-10-08T15:14:36.1776173+08:00",
        "Sequence": 12961,
        "BytesIn": 20839,
        "IFrame": false,
        "PTS": 19447380,
        "DTS": 19441440,
        "Timestamp": 216016000000
      },
      "Name": "h264",
      "State": 0,
      "BPS": 1250146,
      "FPS": 59,
      "Drops": 0,
      "RawSize": 20822,
      "RawPart": [6, 1, 4, 1, 166, 24, 16, 128, 97, 232],
      "PayloadType": 96,
      "SSRC": 72339968,
      "SampleRate": 90000,
      "SequenceHeadSeq": 1,
      "CodecID": 7,
      "GOP": 250,
      "ProfileIdc": 100,
      "LevelIdc": 42,
      "MbWidth": 120,
      "MbHeight": 68,
      "CropLeft": 0,
      "CropRight": 0,
      "CropTop": 0,
      "CropBottom": 4,
      "Width": 1920,
      "Height": 1080
    }
  ],
  "AppName": "live",
  "StreamName": "test1",
  "IsPause": false
}

**Comment by langhuihui** [comment]
用新版本再试一下
