### ISSUE TITLE
关于插件启动问题

### ISSUE THREAD

**Issue by ghost** [Monibuca/engine#93]
可以观看视频教程：

[从零启动 m7s V4](https://www.bilibili.com/video/BV1iq4y147N4/)

[m7s v4 视频教程——插件引入](https://www.bilibili.com/video/BV1sP4y1g7BF/)

官方提供了最新版本的下载链接：

[Linux](https://download.m7s.live/bin/m7s_linux_amd64.tar.gz)
[Linux-arm64](https://download.m7s.live/bin/m7s_linux_arm64.tar.gz)
[Mac](https://download.m7s.live/bin/m7s_darwin_amd64.tar.gz)
[Mac-arm64](https://download.m7s.live/bin/m7s_darwin_arm64.tar.gz)
[Windows](https://download.m7s.live/bin/m7s_windows_amd64.tar.gz)

> 这两个视频只是讲了自己写程序启动引擎和插件，但是通过官方的二进制下载的程序怎么启动插件？
> 要把插件放入哪个位置，然后自动加载了吗？

**Comment by langhuihui** [comment]
官方二进制集成了所有的开源插件，默认读取了 config.yaml下面的配置，里面禁用了 3 个比较消耗资源的插件。二进制无法动态添加插件，插件是通过编译的时候打包在一起的。
