### ISSUE TITLE
rtsp[h265] ------> flv  解析视频包错误

### ISSUE THREAD

**Issue by zhangf901014** [Monibuca/engine#96]
未解析出 帧类型和编码id

**Comment by 2hangchen** [comment]
请问这个问题是怎么解决的？ @zhangf901014

**Comment by zhangf901014** [comment]
没解决，修改了播放器，用他们的 jessibuca 播放器的解封装方式解析flv @2hangchen

**Comment by 2hangchen** [comment]
> 没解决，修改了播放器，用他们的 jessibuca 播放器的解封装方式解析flv @2hangchen

那其实还是视频包有问题的，我们用老版本的engine+flv.js解决了h265的播放问题，升级引擎到最新版后发现h265的包头变了，播放不了了。方便留个联系方式交流一下吗 @zhangf901014

**Comment by zhangf901014** [comment]
18110953365 微信 @2hangchen
