### ISSUE TITLE
把 rtmp 流推去 monibuca，有时候断线重连时 会收到 duplicate publish

### ISSUE THREAD

**Issue by TommyLeng** [Monibuca/engine#98]
我目前需要 7x24 无间断 把rtmp 流推去 monibuca， 我发现有时候网络波动，会断线重连，这时候会收到 duplicate publish 的错误

最后我的解决方法是设 kickexist = true

想问问会不会有其他更好的方法，否则的话我先这样设定了

![image](https://github.com/Monibuca/engine/assets/95701513/224e4a09-b9fa-44dc-ac3d-9a2246043247)

**Comment by langhuihui** [comment]
只能这样了，因为原始连接没有及时退出导致的
