### ISSUE TITLE
为何日志里会输出其他来源的网址信息

### ISSUE THREAD

**Issue by CyberLife-Markus** [Monibuca/engine#99]
<img width="729" alt="image" src="https://github.com/Monibuca/engine/assets/27344136/ab105f79-257b-4a8e-9112-e67ef4b86829">

**Comment by langhuihui** [comment]
有完整一点的日志吗？这个应该和程序无关，可能是你机器上的问题，或者被其他人攻击了

**Comment by CyberLife-Markus** [comment]
日志没了，当时是开了debug在std上输出的。这个花括号内的行就是完整的输出了。
疑惑的点是这里引擎应该输出的是自身http server每次被外部访问的url path，这里能输出别的来源有点诡异

**Comment by langhuihui** [comment]
这不太像是引擎输出的东西啊

**Comment by langhuihui** [comment]
path 理论上不会带上协议头的，难道访问的时候就是 http://xxxxx/http://xxxxxxx 这种？
